# Generated by Django 6.0.3 on 2026-03-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='сategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
